# CMF Routing
cmf_routing:
    chain:
        routers_by_id:
            # enable the DynamicRouter with high priority to allow overwriting configured routes with content
            #cmf_routing.dynamic_router: 200
            # enable the symfony default router with a lower priority
            sonata.page.router: 150
            router.default: 100

# IVORY WYSIWYG EDITOR
ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: standard
            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                # context: my-context # Optional, to upload in a custom context

# Sonata Admin
sonata_admin:
    security:
        #handler:              sonata.admin.security.handler.noop
        handler:              sonata.admin.security.handler.acl
        information:
            # from v1:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR]
            ADMIN:    [MASTER]
            # /v1

            # Prototype
            id:                   []
        admin_permissions:

            # Defaults:
            - CREATE
            - LIST
            - DELETE
            - UNDELETE
            - EXPORT
            - OPERATOR
            - MASTER
        object_permissions:

            # Defaults:
            - VIEW
            - EDIT
            - DELETE
            - UNDELETE
            - OPERATOR
            - MASTER
            - OWNER
        acl_user_manager:     ~         # Name of the user manager service used to retrieve ACL users
    title:                Sonata Admin
    title_logo:           bundles/sonataadmin/logo_title.png
    options:
        html5_validate:                         true      # use html5 validation
        confirm_exit:                           true      # enabled confirmation when quitting with unsaved changes
        use_select2:                            true      # enable select2
        use_icheck:                             true      # enable iCheck
#        pager_links:                            ~         # pager max links to display
        dropdown_number_groups_per_colums:      2         # max items per column in dropdown menu (add button in top nav)
        title_mode:           'both'                      # 'both', 'single_text' or 'single_image'
    dashboard:
        groups:

            # Prototype
            #id:
            #    label:                ~
            #    label_catalogue:      ~
            #    items:                []
            #    item_adds:            []
            #    roles:                []
        blocks:
            #type:                 ~
            #settings:

                # Prototype
                #id:                   []
            #position:             right
    admin_services:

        # Prototype
        id:
            model_manager:        ~
            form_contractor:      ~
            show_builder:         ~
            list_builder:         ~
            datagrid_builder:     ~
            translator:           ~
            configuration_pool:   ~
            router:               ~
            validator:            ~
            security_handler:     ~
            label:                ~
    templates:
        user_block:           SonataAdminBundle:Core:user_block.html.twig
        add_block:            SonataAdminBundle:Core:add_block.html.twig
        layout:               SonataAdminBundle::standard_layout.html.twig
        ajax:                 SonataAdminBundle::ajax_layout.html.twig
        dashboard:            SonataAdminBundle:Core:dashboard.html.twig
        search:               SonataAdminBundle:Core:search.html.twig
        list:                 SonataAdminBundle:CRUD:list.html.twig
        filter:               SonataAdminBundle:Form:filter_admin_fields.html.twig
        show:                 SonataAdminBundle:CRUD:show.html.twig
        show_compare:         SonataAdminBundle:CRUD:show_compare.html.twig
        edit:                 SonataAdminBundle:CRUD:edit.html.twig
        preview:              SonataAdminBundle:CRUD:preview.html.twig
        history:              SonataAdminBundle:CRUD:history.html.twig
        acl:                  SonataAdminBundle:CRUD:acl.html.twig
        history_revision_timestamp:  SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        action:               SonataAdminBundle:CRUD:action.html.twig
        select:               SonataAdminBundle:CRUD:list__select.html.twig
        list_block:           SonataAdminBundle:Block:block_admin_list.html.twig
        search_result_block:  SonataAdminBundle:Block:block_search_result.html.twig
        short_object_description:  SonataAdminBundle:Helper:short-object-description.html.twig
        delete:               SonataAdminBundle:CRUD:delete.html.twig
        batch:                SonataAdminBundle:CRUD:list__batch.html.twig
        batch_confirmation:   SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:       SonataAdminBundle:CRUD:list_inner_row.html.twig
        base_list_field:      SonataAdminBundle:CRUD:base_list_field.html.twig
        pager_links:          SonataAdminBundle:Pager:links.html.twig
        pager_results:        SonataAdminBundle:Pager:results.html.twig
        tab_menu_template:    SonataAdminBundle:Core:tab_menu_template.html.twig


    extensions:

        # Prototype
        id:
            admins:               []
            excludes:             []
            implements:           []
            extends:              []
            instanceof:           []
    persist_filters:      false     # set to true to persist filter settings per admin module in the user's session


# Sonata Block
sonata_block:
#    context_manager: sonata.page.block.context_manager
    default_contexts: [cms]
    context_manager: sonata.page.block.context_manager
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin_doctrine_orm.block.audit:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:

        sonata.media.block.media:
        sonata.media.block.gallery:
        sonata.media.block.feature_media:

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_cache: ~

sonata_classification:
    class:
        tag:          Application\Sonata\ClassificationBundle\Entity\Tag
        category:     Application\Sonata\ClassificationBundle\Entity\Category
        collection:   Application\Sonata\ClassificationBundle\Entity\Collection

    admin:
        tag:
            class:        Sonata\ClassificationBundle\Admin\TagAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        category:
            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        collection:
            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle

# Sonata Doctrine ORM Admin
sonata_doctrine_orm_admin:
    templates:
        types:
            list:
                array:      SonataAdminBundle:CRUD:list_array.html.twig
                boolean:    SonataAdminBundle:CRUD:list_boolean.html.twig
                date:       SonataAdminBundle:CRUD:list_date.html.twig
                time:       SonataAdminBundle:CRUD:list_time.html.twig
                datetime:   SonataAdminBundle:CRUD:list_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_list_field.html.twig
                trans:      SonataAdminBundle:CRUD:list_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_list_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_list_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_list_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_list_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_list_field.html.twig
                identifier: SonataAdminBundle:CRUD:base_list_field.html.twig

            show:
                array:      SonataAdminBundle:CRUD:show_array.html.twig
                boolean:    SonataAdminBundle:CRUD:show_boolean.html.twig
                date:       SonataAdminBundle:CRUD:show_date.html.twig
                time:       SonataAdminBundle:CRUD:show_time.html.twig
                datetime:   SonataAdminBundle:CRUD:show_datetime.html.twig
                text:       SonataAdminBundle:CRUD:base_show_field.html.twig
                trans:      SonataAdminBundle:CRUD:show_trans.html.twig
                string:     SonataAdminBundle:CRUD:base_show_field.html.twig
                smallint:   SonataAdminBundle:CRUD:base_show_field.html.twig
                bigint:     SonataAdminBundle:CRUD:base_show_field.html.twig
                integer:    SonataAdminBundle:CRUD:base_show_field.html.twig
                decimal:    SonataAdminBundle:CRUD:base_show_field.html.twig

# Sonata Formatter
sonata_formatter:
    formatters:
        markdown:
            service: sonata.formatter.text.markdown
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

        #text:
        #    service: sonata.formatter.text.text
        #    extensions:
        #        - sonata.formatter.twig.control_flow
        #        - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig

        #rawhtml:
        #    service: sonata.formatter.text.raw
        #    extensions:
        #        - sonata.formatter.twig.control_flow
        #        - sonata.formatter.twig.gist
        #        - sonata.media.formatter.twig

        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig

        #twig:
        #    service: sonata.formatter.text.twigengine
        #    extensions: [] # Twig formatter cannot have extensions

    ckeditor:
        templates:
            browser: 'SonataFormatterBundle:Ckeditor:browser.html.twig'
            upload: 'SonataFormatterBundle:Ckeditor:upload.html.twig'

# Sonata Media
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                #- sonata.media.provider.podcast # custom

            formats:
                big: { width: 620 ,  quality: 70}
                medium: { width: 300 , height: 150 , quality: 70}
                small: { width: 100 , quality: 70}
                logo: { width: 189 , quality: 70}
                pub: { width: 728 , height: 90 , quality: 70}
        sonata_collection:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
    providers:
        image:
            resizer: sonata.media.resizer.simple #sonata.media.resizer.square
            allowed_mime_types:
              - image/gif
              - image/jpeg
              - image/png
              - image/pjpeg
            allowed_extensions:
              - gif
              - png
              - jpeg
              - jpg

# Sonata News (blog)
sonata_news:
    title:        "Les blogs d'Euradio"
    link:         http://sonata-project.org
    description:  Cool bundles on top of Symfony2
    salt:         'yoiuplaboumsitck'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.collection

    comment:
        notification:
            emails:   [webmaster@euradionantes.eu]
            from:     no-reply@euradionantes.eu
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

    # v1:
    #class:
    #    post:       Application\Sonata\NewsBundle\Entity\Post
    #    tag:        Application\Sonata\NewsBundle\Entity\Tag
    #    comment:    Application\Sonata\NewsBundle\Entity\Comment
    #    category:   Application\Sonata\NewsBundle\Entity\Category
    #    media:      Application\Sonata\MediaBundle\Entity\Media
    #    user:       Application\Sonata\UserBundle\Entity\User
    # /v1

# Sonata Notification
sonata_notification:
    backend: sonata.notification.backend.runtime
    admin:
        enabled: false

# Sonata Page
sonata_page:
    multisite: host
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: {decorate: false} # disable decoration for homepage, key - is a page route

    default_template: default # template key from templates section, used as default for pages
    templates:
        default:  { path: 'SonataPageBundle::layout.html.twig',   name: 'default' }
        ecoute:   { path: 'SonataPageBundle::ecoute2.html.twig',  name: ecoute }
        #2columns: { path: 'SonataPageBundle::2columns_layout.html.twig', name: '2 columns layout' }

    # manage the http errors
    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error

# Sonata SEO
sonata_seo:
    default:          sonata.seo.page.default
    encoding:         UTF-8
    page:
        title:            Sonata Project
        metas:
            name:
                keywords:             foo bar
                description:          The description
                robots:               index, follow

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Sonata Project Sandbox
                'og:description':     A demo of the some rich bundles for your Symfony2 projects

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                #'X-Ua-Compatible':      IE=EmulateIE7

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"

# Sonata User
sonata_user:
    # v2 should be:
    #security_acl: true
    #manager_type: orm # can be orm or mongodb
    #v1:
    security_acl:           false
    impersonating_route:    sonata_user_impersonating
    class:
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata.user.profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]
    # /v1
